### PR TITLE
Added layers support. Fixed documents size import.

### PR DESCRIPTION
**Pull request by ievgennaida**

### CODE REVIEW

**Comment by otuncelli** [comment]
Thanks for the great contribution! Would like test it before merging it down.

I'm currently using [this svg file](https://upload.wikimedia.org/wikipedia/commons/a/ad/Comparison_CD_DVD_HDDVD_BD.svg) for testing and having some problems. 

* The wave shapes (and some other shapes) aren't rendering on layered import mode. Although flat image import mode works fine for these. I don't know if this is a library related issue.

* Also viewbox values are very large for this file. Large values for viewboxes are quite common and rasterization based on these values can cause out of memory problem. This is the main reason why i set it at 500px default.

* Currently flat image import mode renders more correct and works more stable. I suggest flat image mode should remain as default mode for now.

**Comment by ievgennaida** [comment]
Hi, thanks, I will check the file. 
I have tested layers import with default "tiger SVG" and inkscape output. 
500px*ratio for me it's a big issue while I have to restore original document size all the time.
Probably for a big file we need a warning or a button to decrease the original size.
What do you think about this?

**Comment by ievgennaida** [comment]
My suggestion about the size:
If it's smaller than 1280 than it's ok to keep it. 
Reduce this size for a file bigger than 1280.

**Comment by otuncelli** [comment]
Maybe a button to copy from suggested values into the user selection field if it's larger than some hardcoded value. 1280 is okay i think. A warning would also be a good idea.

**Comment by ievgennaida** [comment]
Few more commits have been done. 
For now, those are all the features I would like to have.

**Comment by ievgennaida** [comment]
Also could you please add a release version as a form title?

**Comment by otuncelli** [comment]
Looks good to me. Thanks! Yes, I'll add a version information to form title. Thanks for reminding me.

I'll test this for a while then if everything is okay merge down the PR and prepare a new release in the following days.

**Comment by ievgennaida** [comment]
🙋 Super

**Pull request merged**
